### ISSUE TITLE
Чтение в слух Microsoft Edge не работает

### ISSUE THREAD

**Issue by kutukvpavel** [bookpauk/liberama#24]
Не работает ни средство иммерсионного чтения, ни, соответственно, чтение в слух в Edge. Почему-то не находит текст, открывается, фактически, пустая страница:

![image](https://user-images.githubusercontent.com/41666738/143788416-79245468-be54-4e28-a097-15d9f0550789.png)

То же самое, как с локальными файлами, так и со ссылками. Пробовал только на FB2, но, полагаю, что формат не несёт никакой разницы. Видимо это как-то связано со структурой отображаемого документа. Очень неприятная мелочь.

**Comment by bookpauk** [comment]
Т.к. читалка представляет собой SPA (Single Page Application), то весь контент в ней формируется динамически (через выполнение кода).
Соответственно, использование инструментов, получающих на вход статические данные - к примеру, текст веб страниц - бесполезно.

Как обходной путь, можно воспользоваться в читалке возможностью "Скопировать текст со страницы" для копирования куска чистого текста, либо всей книги (регулируется в настройках). Далее можно вставить его в стороннюю читалку, либо сохранить как отдельную страницу локально и попробовать открыть в Edge. Также можно сохранять fb2-файл книги из читалки.

**Comment by kutukvpavel** [comment]
Спасибо. Я уже давно далёк от веб-разработки, поэтому не буду притворяться, что понял :)
Но раз это архитектурная особенность, то можно закрывать. Это не сильно приоритетный вопрос.
