### ISSUE TITLE
Сборка для Linux arm64

### ISSUE THREAD

**Issue by xboxones1** [bookpauk/liberama#39]
Добрый. 
Сервер теперь собирается под arm, то неплохо бы и для читалки добавить поддержку.

**Comment by bookpauk** [comment]
Да, добавлю сборку, как закончу с inpx-web. И вообще сборку релизов liberama добавлю, с описанием настройки.

Inpx-web, кстати, встраивается в читалку в раздел "Сетевая библиотека". Еще, правда, не обновлял читалку с его поддержкой (все пока в девелопе). Книги сразу будут открываться в читалке по клику на "(читать)" из сетевой библиотеки.
