### ISSUE TITLE
Проблемка с сетевыми библиотеками при входе снаружи

### ISSUE THREAD

**Issue by ra3ggi** [bookpauk/liberama#42]
Приветствую! 
Установил liberama - в локальной сети все работает. 
Пробросил роутером портом "наружу". При входе через инет сама читалка работает, а при нажатии на "Сетевые библиотеки" - ненадолго появляется "Загрузка..." в левом верхнем углу и все - серый экран.
Что можно сделать?

**Comment by bookpauk** [comment]
Здравствуйте.
Какую версию liberama используете? В 1.1.3 были исправления по этому поводу.

Если в 1.1.3 такое же поведение, посмотрите пож-та, может какие-то ошибки присутствуют в консоли (F12) инструментов разработчика.

**Comment by ra3ggi** [comment]
Приветствую!
Я немного не о том.
В версии 1.1.3 была поправлена "переброска" книги из сетевой библиотеки в читалку - это теперь работает. 
У меня сервер с читалкой не "смотрит" в инет , а находится внутри локальной сети. Внутри этой сети - все работает.
Видимость этой читалки через инет обеспечивается пробросом порта в роутере. Т.е. в роутере прописано "если идет обращение "внешний IP: порт", то пробросить на "внутренний IP: порт"". Ну , обычная схема.
Так вот , если входить в читалку из инета , то сама читалка работает, а вот открытие сетевой библиотеки не происходит. Не совсем понятно почему, а инструментов для настройки у меня почти нет ( в json таких параметров нет)
Просто такая схема применения liberama может быть не только у меня - не все же будут  ставить её на выделенный сервер (  на выделенном сервере, смотрящим прямо в инет, уверен , таких проблем не будет).

**Comment by bookpauk** [comment]
В 1.1.3 вносились изенения именно по вашей проблеме, только что проверил - все работает с пробросом портов в роутере.
Попробуйте в свежем браузере зайти, или с очисткой данных сайта (удалит все настройки/сохраненные локально книги: F12 - Application - Clear site data). 

Если ошибка повторяется - приведите показания консоли (F12 - Console).

**Comment by ra3ggi** [comment]
Да , начиная с  какого-то обновления - все заработало как надо. 
Спасибо за отличный  проект - прекрасен как функционал , так и скорость работы ! 
У меня как inpx-web ( с локальной библиотекой Флибуста) , так и liberama установлены на TrueNAS Scale, и взаимодополняют друг друга.
