### ISSUE TITLE
local reading from inpx-web troubles

### ISSUE THREAD

**Issue by sata0ata** [bookpauk/liberama#44]
на одном сервере поднято inpx-web и liberama
на inpx нажимаю "читать", в ссылке в конфиге указан сервер liberama
выдаёт ошибку:
![изображение](https://user-images.githubusercontent.com/94180068/236690193-9cf30f27-85dc-455e-91fe-4b9d1fba7893.png)
ip и порт смотрят в интернет
при этом если книгу скачать из inpx а потом загрузить в либераму то всё ок...

дополнительный вопрос:
если я поднял inpx, я же поднял "сетевую библиотеку"? где указать в либераме как добраться до локальной библиотеки?

и последнее:
есть ли inpx+liberama 2 в одном?
указываешь где лежат локальные .inpx и всё

сервер на дебиане

**Comment by sata0ata** [comment]
я сначала подумал, дело в пароле установленном в конфиг-файле inpx-web, убрал пароль, перезапустил службы, ошибка сохранилась

**Comment by bookpauk** [comment]
Если оба на одном сервере, они могут не видеть друг-друга. Попробуйте на самом сервере wget'ом или сurl'ом скачать ссылку на книгу, которую выдает inpx-web. Liberama же по точно такой же ссылке книгу скачивает, если все правильно настроено.

Два в одном нету, просто в либераме в Сетевой библиотеке добавьте закладку на свой inpx-web, тогда во фрейме при нажатии "Читать" с сайта inpx-web книга сразу будет отправляться в читалку (но загружается она все равно по той же ссылке, что выше)
