### ISSUE TITLE
[Feature request] Android app

### ISSUE THREAD

**Issue by eugenov** [bookpauk/liberama#46]
Есть ли шанс увидеть bookpauk-инфраструктуру?  Google books сейчас безальтернативный монополист, если не учитывать всякие костылёвые решения.
Что я представляю себе под этим:
- приложение для Андроид, подключающееся к liberama, как фронтенду inpx-web
- единый сервер (liberama), который сохраняет закладки, книжные полки, позицию чтения каждой книги, заметки для пользователя
- возможность использовать вышеуказанные фичи как онлайн, так и оффлайн
- возможность выкачать не только fb2, но и epub, mobi, и тп.

**Comment by bookpauk** [comment]
Шансов мало.
А чем не устраивает работа читалки из Chrome в Android? Да, интерфейс немного неудобен (не совсем адаптирован) для мобильных, но пользоваться можно.
Т.е. связка "устройство+Chrome+сайт omnireader.ru (liberama.top)+Сетевая библиотека (в которой выбран свой сервер inpx-web)" у меня работает на всех устройствах. Спокойно читаю в планшете, на дексктопе, иногда в телефоне параллельно одну и ту же книгу.
