### ISSUE TITLE
Feature request: support `Remote-User`

### ISSUE THREAD

**Issue by Jipok** [bookpauk/liberama#48]
Я пробовал множество различных self-hosted приложений/сервисов и со временем пришел к идее, что пароли очень неудобны и небезопасны. К счастью, оказалось, что различные популярные обратные прокси(вместе с авторизующими middleware) передают заголовок `Remote-User`(иногда `X-Forwarded-User`). И некоторые приложения (например: [grist](https://support.getgrist.com/install/forwarded-headers/#forwarded-headers)) могут быть настроены на этот метод аутентификации. Еще больше их может быть настроено на публичный доступ (то есть отключение аутентификации) и работают отлично за авторизирующими обратными прокси.
Со временем я написал минималистичный и удобный(для меня) авторизирующий обратный прокси [Jauth](https://github.com/Jipok/Jauth). Хостинг различных приложений стал очень удобным и безопасным.

Собственно я предлагаю добавить опцию - вместо ключей доступа использовать предоставленное прокси-сервером имя пользователя.
Вот так для вашего сервера выглядит запрос вашего клиента через мой прокси:
```
GET /ws HTTP/1.1
Host: lib.jipok.ru
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3
Cache-Control: no-cache
Connection: Upgrade
Cookie: jauth_token=1707933765-BFJQ265v11Dw77XJEhFel6Pl
Origin: https://lib.jipok.ru
Pragma: no-cache
Remote-User: Jipok
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: websocket
Sec-Fetch-Site: same-origin
Sec-Websocket-Extensions: permessage-deflate
Sec-Websocket-Key: uUFccj7h+yiskRFTZlPM3w==
Sec-Websocket-Version: 13
Upgrade: websocket
X-Forwarded-For: 192.168.1.1
X-Forwarded-Host: lib.jipok.ru
X-Forwarded-Proto: https
X-Forwarded-User: Jipok
```
Чтобы понять что такое Jauth и как он выглядит я дал вам доступ через https://github.com/bookpauk.keys
Сайт: https://lib.jipok.ru

**Comment by bookpauk** [comment]
Ну это же permissioned система для личного пользования получится. Ключи доступа предлагают permissionless вариант для доступа любого человека, без сбора личной информации о нем. Да, безопасность хромает, но мы тут не банковскую систему строим.

**Comment by Jipok** [comment]
> Ну это же permissioned система для личного пользования получится. Ключи доступа предлагают permissionless вариант для доступа любого человека, без сбора личной информации о нем.

Я с данной терминологей не знаком.
У вас же сервер всё равно хранит список книг для определённого ключа? Или там всё зашифровано?
В любом случае реализовать возможность входа по хидеру не должно быть сложно.
Я бы сам попытался будь там другой бэкенд, но js вызывает у меня боль и сейчас нет времени разбираться с ним.

> вариант для доступа любого человека

Не вариант для меня и как мне кажется многих кто размещает у себя флибусту. Получить бан от роскомнадзора не хочется.

> без сбора личной информации о нем

Учитывая что размещается для личного пользования(+ расшарить паре друзей/родственников) я не вижу ничего плохо в том что админ в теории сможет увидеть кто что читает. Мне вот это лично не интересно.
А вот возможность войти с любого устройства и без лишних телодвижений продолжить чтение это круто.

Я не сам тему с авторизацией по хидеру придумал. Есть более популярные решения чем моё: https://github.com/oauth2-proxy/oauth2-proxy

**Comment by bookpauk** [comment]
> У вас же сервер всё равно хранит список книг для определённого ключа? Или там всё зашифровано

Да, все шифруется на стороне клиента ключом доступа, сам ключ на сервере не хранится, только его хеш.

> Не вариант для меня и как мне кажется многих кто размещает у себя флибусту. Получить бан от роскомнадзора не хочется.

Ну можно же "спрятать" приложение за фронтенд-сервер типа nginx и прикрутить тутда любые системы аутентификации. А само приложение универсально различает клиентов на базе ключа доступа, который выдается клиентом (браузером) в случае его отсутствия.

**Comment by bookpauk** [comment]
Изначально проект разрабатывался как легко разворачиваемый сайт для чтения ресурсов интернета, доступный для всех. 
https://omnireader.ru/
https://liberama.top/

Но было сделано все, чтобы облегчить разворачивание для личного пользования. А персонализация под себя - это уже вкус и цвет каждого отдельного разработчика.

**Comment by bookpauk** [comment]
Закрываю, т.к. предложение не соответствует идее проекта.
