### ISSUE TITLE
Add support for armhf platform

### ISSUE THREAD

**Issue by cryptoqube777** [bookpauk/liberama#49]
Tried to build package on OrangePi and RaspberryPi with armhf architecture, but failed.

**Comment by bookpauk** [comment]
You can try native way of running nodejs apps, something like:

# install nodejs v16 and above:
curl -s https://deb.nodesource.com/setup_16.x | sudo bash
sudo apt install nodejs -y

# preparing
git clone https://github.com/bookpauk/inpx-web
cd inpx-web
npm i
npm run build:client && node build/prepkg.js linux

# delete development-env file, to run liberama in production mode
rm ./server/config/application_env

# run app, setting appdir path:
node server --app-dir=.liberama
